spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: admin
        password: admin

    jpa:
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        hbm2ddl:
            auto: validate
        generate-ddl: false
    show-sql: true
