spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
logging:
    level:
        org.hibernate.SQL: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

